"""timer_value

Revision ID: 1ef0dca4b091
Revises: 27276387f606
Create Date: 2022-09-24 09:12:06.420200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef0dca4b091'
down_revision = '27276387f606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fightsDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fight_timer', sa.Integer(), nullable=True))
        batch_op.drop_column('timer_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fightsDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timer_value', sa.INTEGER(), nullable=True))
        batch_op.drop_column('fight_timer')

    # ### end Alembic commands ###
