"""timer_value

Revision ID: 27276387f606
Revises: 4642df6e30d2
Create Date: 2022-09-24 08:13:47.444260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27276387f606'
down_revision = '4642df6e30d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fightsDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timer_value', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fightsDB', schema=None) as batch_op:
        batch_op.drop_column('timer_value')

    # ### end Alembic commands ###
