"""fight_status

Revision ID: 4642df6e30d2
Revises: 91be65f27fa4
Create Date: 2022-09-23 11:54:49.711090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4642df6e30d2'
down_revision = '91be65f27fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fight_statusDB',
    sa.Column('fight_status_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('fight_status_code', sa.Integer(), nullable=True),
    sa.Column('fight_status_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitionsDB.competition_id'], name=op.f('fk_fight_statusDB_competition_id_competitionsDB')),
    sa.PrimaryKeyConstraint('fight_status_id', name=op.f('pk_fight_statusDB'))
    )
    with op.batch_alter_table('fightsDB', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_fightsDB_fight_status_fight_statusDB'), 'fight_statusDB', ['fight_status'], ['fight_status_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fightsDB', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_fightsDB_fight_status_fight_statusDB'), type_='foreignkey')

    op.drop_table('fight_statusDB')
    # ### end Alembic commands ###
