"""queue

Revision ID: 48af5c7967c9
Revises: af3d5f912a03
Create Date: 2022-09-17 15:01:38.958856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48af5c7967c9'
down_revision = 'af3d5f912a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queueDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competition_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_queueDB_competition_id_competitionsDB'), 'competitionsDB', ['competition_id'], ['competition_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queueDB', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_queueDB_competition_id_competitionsDB'), type_='foreignkey')
        batch_op.drop_column('competition_id')

    # ### end Alembic commands ###
