"""13

Revision ID: 7f6b01fbc278
Revises: dc2a9cbfc2f6
Create Date: 2022-09-16 13:48:56.370423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6b01fbc278'
down_revision = 'dc2a9cbfc2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tatamiDB',
    sa.Column('tatami_id', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tatami_id', name=op.f('pk_tatamiDB'))
    )
    with op.batch_alter_table('roundsDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tatami_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_roundsDB_tatami_id_agecategoriesDB'), 'agecategoriesDB', ['tatami_id'], ['age_cat_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roundsDB', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_roundsDB_tatami_id_agecategoriesDB'), type_='foreignkey')
        batch_op.drop_column('tatami_id')

    op.drop_table('tatamiDB')
    # ### end Alembic commands ###
