"""queue_sort_index

Revision ID: 91be65f27fa4
Revises: 150743a84d60
Create Date: 2022-09-19 08:12:14.258018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91be65f27fa4'
down_revision = '150743a84d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fightsDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_sort_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('queue_catagory_sort_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fightsDB', schema=None) as batch_op:
        batch_op.drop_column('queue_catagory_sort_index')
        batch_op.drop_column('queue_sort_index')

    # ### end Alembic commands ###
