"""13

Revision ID: 96c68df81fd7
Revises: c3f6b8db20b8
Create Date: 2022-09-16 14:30:20.227507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c68df81fd7'
down_revision = 'c3f6b8db20b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tatamiDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competition_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tatamiDB_competition_id_competitionsDB'), 'competitionsDB', ['competition_id'], ['competition_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tatamiDB', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tatamiDB_competition_id_competitionsDB'), type_='foreignkey')
        batch_op.drop_column('competition_id')

    # ### end Alembic commands ###
