"""queue

Revision ID: af3d5f912a03
Revises: a6b56d0f66b4
Create Date: 2022-09-17 10:40:19.156657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3d5f912a03'
down_revision = 'a6b56d0f66b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queueDB',
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('tatami_id', sa.Integer(), nullable=True),
    sa.Column('fight_id', sa.Integer(), nullable=True),
    sa.Column('queue_sort_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fightsDB.fight_id'], name=op.f('fk_queueDB_fight_id_fightsDB')),
    sa.ForeignKeyConstraint(['tatami_id'], ['tatamiDB.tatami_id'], name=op.f('fk_queueDB_tatami_id_tatamiDB')),
    sa.PrimaryKeyConstraint('queue_id', name=op.f('pk_queueDB'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queueDB')
    # ### end Alembic commands ###
