"""13

Revision ID: c3f6b8db20b8
Revises: 7f6b01fbc278
Create Date: 2022-09-16 14:04:25.140708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f6b8db20b8'
down_revision = '7f6b01fbc278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tatamiDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tatami_name', sa.String(), nullable=True))
        batch_op.drop_column('round_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tatamiDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('tatami_name')

    # ### end Alembic commands ###
