"""added_time

Revision ID: c896c236d50c
Revises: a11e8d27f668
Create Date: 2022-09-15 22:34:22.118900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c896c236d50c'
down_revision = 'a11e8d27f668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitionsDB', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitionsDB', schema=None) as batch_op:
        batch_op.drop_column('added_time')

    # ### end Alembic commands ###
